title: Talking Robotics
logo: /assets/img/logo.jpg
description: Series of seminars on robotics and its interaction with other relevant research fields.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
