title: Talking Robotics
logo: /assets/img/logo.jpg
description: Promoting reflections and dialogue on robotics and its interaction with other relevant research fields.
organization: patricia, silvia, miguel, joana
email: talkingrobotics {at} gmail {dot} com 
twitter: https://twitter.com/talkingrobotics
youtube: https://www.youtube.com/channel/UC-ildOqpbG04qaNXbhNYqMQ?view_as=subscriber
