title: Talking Robotics
logo: /assets/img/logo.jpg
description: Promoting reflections and dialogue on robotics and its interaction with other relevant research fields.
social-network-links:
  email: "talkingrobotics[at]gmail[dot]com"
  twitter: [twitter](https://twitter.com/talkingrobotics)
  youtube: [youtube](https://www.youtube.com/channel/UC-ildOqpbG04qaNXbhNYqMQ?view_as=subscriber)
organization: Organized by [Patrícia Alves Oliveira](https://patricialvesoliveira.com/), [Silvia Tulli](https://silviatulli.com/), [Miguel Vasco](https://miguelsvasco.github.io/), [Joana Campos](http://www.joanacfcampos.com/)