title: Talking Robotics
logo: /assets/img/logo.jpg
description: Promoting reflections and dialogue on robotics and its interaction with other relevant research fields.
organization: patricia, silvia, miguel, joana
social-network-links: twitter, youtube, email
email: email
twitter: twitter
youtube: youtube
